version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_DL_API=http://backend:5050/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    environment:
      - SERVER_PORT=5050
      - MONGO_URI=${MONGO_URI}
      - DL_API=http://python-api:8000/code-smell-detector/analyze
    depends_on:
      - python-api

  python-api:
    build: ./ai-services
    ports:
      - "8000:8000"
    env_file:
      - ./ai-services/.env
